/*
 * This source file was generated by the Gradle 'init' task
 */
package mars;


public class Main {
    
    //user.dir will make sure that all logs are generated inside the projet folder starting from app
    private static final String LOGGER_FILE_PATH = System.getProperty("user.dir") + "/logs/test.txt";

    public static void main(String[] args) {
        TestLogger testLogger = new TestLogger(LOGGER_FILE_PATH);
        testLogger.runTest();
    }
}